# Generated by Django 5.0 on 2023-12-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_description_comment_text_remove_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='is_active',
        ),
    ]
