# Generated by Django 5.0 on 2023-12-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
