# Generated by Django 5.0 on 2024-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Programming', 'Programming'), ('Internet', 'Internet'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('Othrs', 'Others')], default='Othrs', max_length=255),
        ),
    ]
